### ISSUE TITLE
No .json

### ISSUE THREAD

**Issue by Lolicon-Mindustry** [DE3000/Manufacry-kt#1]
![Screenshot_20200306-084907](https://user-images.githubusercontent.com/59752736/76059440-83855b00-5f87-11ea-90f9-01dc6092f515.jpg)

When i tried to import this mod to mindustry

**Comment by DE3000** [comment]
This mod was made using the Java mod API which was abandoned for the Javascript mod API. I will be redoing the mod with Javascript.
